### PR TITLE
ConsoleLib documents generation

### LINKED ISSUE #80: ConsoleLib documents generation
- [x]  Generate documents into the `doc` directory in project
- [x] Generate the documents of all user defined types and methods
- [x] Add branches and/or PR's to the issue
- [x] Generic format of the branch should be like that `doc/<lib name>/<your tag>` i.e. `doc/imageprocessinglib/okrn`

### LINKED ISSUE #90: Bug: Wrong format specifiers of write functions
write functions that have float typed parameters have wrong type parameters.

### PR DESCRIPTION
**Pull request by edaakyil**
Documented: #80

### CODE REVIEW

File: ConsoleLib/src/main/java/com/karandev/io/util/console/CommandLineArgs.java [hunk 1]
```diff
@@ -1,37 +1,77 @@
...
-	FILE        : CommandLineArgs.java
-	AUTHOR      : Oğuz Karan
-	LAST UPDATE : 18.02.2024
-
-	Utility class for command line arguments check
-
-	Copyleft (c) 1993 by C and System Programmers Association (CSD)
-	All Rights Free
------------------------------------------------------------------------*/
+/*
```
Comment (oguzkaran) [inline ConsoleLib/src/main/java/com/karandev/io/util/console/CommandLineArgs.java]: It is not appropriate to write comments here

File: ConsoleLib/src/main/java/com/karandev/io/util/console/CommandLineArgs.java [hunk 2]
```diff
@@ -1,37 +1,77 @@
...
+/**
+ * Utility class for validating command line argument counts.
+ *
+ * <p>Provides static methods to check if the number of command line arguments
+ * matches specific conditions (equals, not equals, greater, less, etc.).
+ * If a check fails, an error message is printed and the application exits
+ * with the specified exit code.
+ *
+ * @author JavaApp2-Jan-2024 Group
+ * @version 1.0.0
```
Comment (oguzkaran) [inline ConsoleLib/src/main/java/com/karandev/io/util/console/CommandLineArgs.java]: Please delete the version. You can write `since` annotation here after the initial versions.

File: ConsoleLib/src/main/java/com/karandev/io/util/console/CommandLineArgs.java [hunk 3]
```diff
@@ -1,37 +1,77 @@
...
 
+/**
+ * Utility class for validating command line argument counts.
+ *
+ * <p>Provides static methods to check if the number of command line arguments
+ * matches specific conditions (equals, not equals, greater, less, etc.).
+ * If a check fails, an error message is printed and the application exits
+ * with the specified exit code.
+ *
+ * @author JavaApp2-Jan-2024 Group
```
Comment (oguzkaran) [inline ConsoleLib/src/main/java/com/karandev/io/util/console/CommandLineArgs.java]: Please Write the author as CSD Development group

File: ConsoleLib/src/main/java/com/karandev/io/util/console/Console.java [hunk 4]
```diff
@@ -759,156 +1444,316 @@ public static BigInteger readBigInteger(String msg, String errMsg, int radix)
...
     }
 
+    /**
+     * Writes a float value followed by a newline to standard output.
+     *
+     * @param val the float value to be written
+     */
     public static void writeLine(float val)
     {
         writeLine("%d", val);
```
[the remark this answers is not in the document]
Comment (Mehmed6) [reply ConsoleLib/src/main/java/com/karandev/io/util/console/Console.java:1707]: In the `writeLine(float)` method, using `%d` is incorrect. When a float value is passed, it throws an exception. `%f` should be used instead.

**Review by Mehmed6 — COMMENTED** [review]
In the `write(float)` and `writeLine(float)`  methods, using `%d` is incorrect. When a float value is passed, it throws an exception. `%f` should be used instead.

**Comment by oguzkaran** [comment]
@edaakyil can you please take an action for that bug: [Wrong format specifiers](https://github.com/oguzkaran/Java-Libraries-Development/issues/90)

File: ConsoleLib/pom.xml [hunk 5]
```diff
@@ -13,7 +13,7 @@
 
     <groupId>com.karandev</groupId>
     <artifactId>com-karandev-util-console</artifactId>
-    <version>2.0.0</version>
+    <version>1.0.0</version>
```
[the remark this answers is not in the document]
Comment (oguzkaran) [reply ConsoleLib/pom.xml:16]: @edaakyil  we can skip that comment.

**Comment by oguzkaran** [comment]
@edaakyil please resolve conversations that you fixed then @Mehmed6  and I will review as soon as possible

**Comment by edaakyil** [comment]
Fixes: #90

**Review by oguzkaran — DISMISSED** [review]

**Comment by oguzkaran** [comment]
We will not use extra branch for that repository anymore. So, I changed the target branch to main @edaakyil

**Review by oguzkaran — APPROVED** [review]

**Review by Mehmed6 — APPROVED** [review]
